use std::fmt::Write;
use std::path::Path;
use std::process::Command;

use crate::backend::{CadBackend, OutputFiles};
use crate::cad::{CadAssembly, CadNode, CadPrimitive, Child, Transform};

pub struct OpenSCADBackend;

impl CadBackend for OpenSCADBackend {
    fn render(&self, model: &CadAssembly, output_dir: &Path) -> anyhow::Result<OutputFiles> {
        std::fs::create_dir_all(output_dir)?;

        let scad_path = output_dir.join("conveyor.scad");
        let stl_path = output_dir.join("conveyor.stl");

        let scad_source = generate_openscad(model);
        std::fs::write(&scad_path, &scad_source)?;

        let output = Command::new("openscad")
            .arg("-o")
            .arg(&stl_path)
            .arg(&scad_path)
            .output()
            .map_err(|e| {
                if e.kind() == std::io::ErrorKind::NotFound {
                    anyhow::anyhow!(
                        "OpenSCAD not found. Install it or add it to PATH."
                    )
                } else {
                    anyhow::anyhow!("failed to execute openscad: {e}")
                }
            })?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("openscad failed: {stderr}");
        }

        Ok(OutputFiles {
            scad_path: Some(scad_path),
            stl_path: Some(stl_path),
            step_path: None,
            bom_path: None,
        })
    }
}

fn generate_openscad(assembly: &CadAssembly) -> String {
    let mut code = String::new();
    writeln!(code, "// Generated by Mekhanikçi").unwrap();
    writeln!(code, "$fn = 32;").unwrap();
    writeln!(code).unwrap();

    writeln!(code, "module {}() {{", assembly.name).unwrap();
    for child in &assembly.children {
        write_node(child, &mut code, 1);
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();
    writeln!(code, "{}();", assembly.name).unwrap();
    code
}

fn write_transform(transform: &Transform, code: &mut String, indent: usize) {
    let pad = "    ".repeat(indent);
    let t = &transform.translation;
    let r = &transform.rotation;

    let has_trans = t != &[0.0, 0.0, 0.0];
    let has_rot = r != &[0.0, 0.0, 0.0];

    if has_trans {
        write!(
            code,
            "{}translate([{:.1}, {:.1}, {:.1}]) ",
            pad, t[0], t[1], t[2]
        )
        .unwrap();
    } else {
        write!(code, "{}", pad).unwrap();
    }
    if has_rot {
        write!(code, "rotate([{:.1}, {:.1}, {:.1}]) ", r[0], r[1], r[2]).unwrap();
    }
}

fn write_node(child: &Child, code: &mut String, indent: usize) {
    match &*child.node {
        CadNode::Part(part) => {
            for prim in &part.primitives {
                write_transform(&child.transform, code, indent);
                match prim {
                    CadPrimitive::Box { x, y, z } => {
                        writeln!(code, "cube([{:.1}, {:.1}, {:.1}], center = true);", x, y, z)
                            .unwrap();
                    }
                    CadPrimitive::Cylinder { r, h } => {
                        writeln!(code, "cylinder(r = {:.1}, h = {:.1}, center = true);", r, h)
                            .unwrap();
                    }
                }
            }
        }
        CadNode::Assembly(assembly) => {
            let pad = "    ".repeat(indent);
            write_transform(&child.transform, code, indent);
            writeln!(code, "union() {{").unwrap();
            for child in &assembly.children {
                write_node(child, code, indent + 1);
            }
            writeln!(code, "{}}}", pad).unwrap();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cad::CadPart;

    fn sample_assembly() -> CadAssembly {
        CadAssembly {
            name: "test".into(),
            children: vec![Child {
                node: Box::new(CadNode::Part(CadPart {
                    name: "block".into(),
                    primitives: vec![CadPrimitive::Box {
                        x: 10.0,
                        y: 20.0,
                        z: 30.0,
                    }],
                })),
                transform: Transform::default(),
            }],
        }
    }

    #[test]
    fn test_generate_openscad_basic() {
        let assembly = sample_assembly();
        let code = generate_openscad(&assembly);
        assert!(code.contains("cube([10.0, 20.0, 30.0]"));
        assert!(code.contains("module test()"));
        assert!(code.contains("test();"));
    }

    #[test]
    fn test_generate_openscad_with_transform() {
        let assembly = CadAssembly {
            name: "test".into(),
            children: vec![Child {
                node: Box::new(CadNode::Part(CadPart {
                    name: "block".into(),
                    primitives: vec![CadPrimitive::Box {
                        x: 10.0,
                        y: 10.0,
                        z: 10.0,
                    }],
                })),
                transform: Transform {
                    translation: [100.0, 200.0, 300.0],
                    rotation: [0.0, 0.0, 0.0],
                },
            }],
        };
        let code = generate_openscad(&assembly);
        assert!(code.contains("translate([100.0, 200.0, 300.0])"));
    }
}
