use std::fmt::Write;
use std::path::Path;
use std::process::Command;

use crate::backend::{CadBackend, OutputFiles};
use crate::cad::{CadAssembly, CadNode, CadPrimitive, Child, Transform};

pub struct OpenSCADBackend {
    pub binary_path: String,
}

impl OpenSCADBackend {
    pub fn new(binary_path: impl Into<String>) -> Self {
        Self {
            binary_path: binary_path.into(),
        }
    }
}

impl CadBackend for OpenSCADBackend {
    fn render(&self, model: &CadAssembly, output_dir: &Path) -> anyhow::Result<OutputFiles> {
        std::fs::create_dir_all(output_dir)?;

        let scad_path = output_dir.join("conveyor.scad");
        let stl_path = output_dir.join("conveyor.stl");
        let bom_path = output_dir.join("bom.csv");

        let scad_source = generate_openscad(model);
        std::fs::write(&scad_path, &scad_source)?;

        let output = Command::new(&self.binary_path)
            .arg("-o")
            .arg(&stl_path)
            .arg(&scad_path)
            .output()?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("OpenSCAD rendering failed: {}", stderr);
        }

        generate_bom(model, &bom_path)?;

        Ok(OutputFiles {
            scad_path: Some(scad_path),
            stl_path: Some(stl_path),
            step_path: None,
            bom_path: Some(bom_path),
        })
    }
}

fn generate_openscad(assembly: &CadAssembly) -> String {
    let mut code = String::new();
    writeln!(code, "// Generated by Mekhanikçi").unwrap();
    writeln!(code, "$fn = 32;").unwrap();
    writeln!(code).unwrap();

    writeln!(code, "module {}() {{", assembly.name).unwrap();
    for child in &assembly.children {
        write_node(child, &mut code, 1);
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();
    writeln!(code, "{}();", assembly.name).unwrap();
    code
}

fn write_transform(transform: &Transform, code: &mut String, indent: usize) {
    let pad = "    ".repeat(indent);
    let t = &transform.translation;
    let r = &transform.rotation;

    let has_trans = t != &[0.0, 0.0, 0.0];
    let has_rot = r != &[0.0, 0.0, 0.0];

    if has_trans {
        write!(code, "{}translate([{:.1}, {:.1}, {:.1}]) ", pad, t[0], t[1], t[2]).unwrap();
    } else {
        write!(code, "{}", pad).unwrap();
    }
    if has_rot {
        write!(code, "rotate([{:.1}, {:.1}, {:.1}]) ", r[0], r[1], r[2]).unwrap();
    }
}

fn write_node(child: &Child, code: &mut String, indent: usize) {
    match &*child.node {
        CadNode::Part(part) => {
            for prim in &part.primitives {
                write_transform(&child.transform, code, indent);
                match prim {
                    CadPrimitive::Box { x, y, z } => {
                        writeln!(code, "cube([{:.1}, {:.1}, {:.1}], center = true);", x, y, z).unwrap();
                    }
                    CadPrimitive::Cylinder { r, h } => {
                        writeln!(code, "cylinder(r = {:.1}, h = {:.1}, center = true);", r, h).unwrap();
                    }
                }
            }
        }
        CadNode::Assembly(assembly) => {
            let pad = "    ".repeat(indent);
            write_transform(&child.transform, code, indent);
            writeln!(code, "union() {{").unwrap();
            for child in &assembly.children {
                write_node(child, code, indent + 1);
            }
            writeln!(code, "{}}}", pad).unwrap();
        }
    }
}

fn generate_bom(assembly: &CadAssembly, path: &Path) -> anyhow::Result<()> {
    let mut csv = String::new();
    csv.push_str("Part,Quantity,Notes\n");
    collect_bom_items(assembly, &mut csv);
    std::fs::write(path, csv)?;
    Ok(())
}

fn collect_bom_items(assembly: &CadAssembly, csv: &mut String) {
    for child in &assembly.children {
        match &*child.node {
            CadNode::Part(part) => {
                let qty = 1;
                let dims: Vec<String> = part
                    .primitives
                    .iter()
                    .map(|p| match p {
                        CadPrimitive::Box { x, y, z } => format!("{:.0}x{:.0}x{:.0}", x, y, z),
                        CadPrimitive::Cylinder { r, h } => format!("r{:.0} h{:.0}", r, h),
                    })
                    .collect();
                let notes = dims.join(", ");
                writeln!(csv, "{},{},{}", part.name, qty, notes).unwrap();
            }
            CadNode::Assembly(sub) => {
                collect_bom_items(sub, csv);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cad::CadPart;

    fn sample_assembly() -> CadAssembly {
        CadAssembly {
            name: "test".into(),
            children: vec![Child {
                node: Box::new(CadNode::Part(CadPart {
                    name: "block".into(),
                    primitives: vec![CadPrimitive::Box {
                        x: 10.0,
                        y: 20.0,
                        z: 30.0,
                    }],
                })),
                transform: Transform::default(),
            }],
        }
    }

    #[test]
    fn test_generate_openscad_basic() {
        let assembly = sample_assembly();
        let code = generate_openscad(&assembly);
        assert!(code.contains("cube([10.0, 20.0, 30.0]"));
        assert!(code.contains("module test()"));
        assert!(code.contains("test();"));
    }

    #[test]
    fn test_generate_openscad_with_transform() {
        let assembly = CadAssembly {
            name: "test".into(),
            children: vec![Child {
                node: Box::new(CadNode::Part(CadPart {
                    name: "block".into(),
                    primitives: vec![CadPrimitive::Box {
                        x: 10.0,
                        y: 10.0,
                        z: 10.0,
                    }],
                })),
                transform: Transform {
                    translation: [100.0, 200.0, 300.0],
                    rotation: [0.0, 0.0, 0.0],
                },
            }],
        };
        let code = generate_openscad(&assembly);
        assert!(code.contains("translate([100.0, 200.0, 300.0])"));
    }
}
